### ISSUE TITLE
UEH 的部署文档似乎存在一些问题

### ISSUE THREAD

**Issue by FeiYuJun** [china-alert/ueh#1]
# 下载源 http://123.60.39.174:18181/docs/ueh/ueh-1g3vvvhmrv17p
## mysql postgresql 实际字段参数值错误
```bash  
update ueh_admin.t_view_page_datasource set url=replace(url,'127.0.0.1','umc门户数据库地址'),password=replace(password,'123456','umc门户数据库密码')  where database_type='mysql';
update ueh_admin.t_view_page_datasource set url=replace(url,'127.0.0.1','postgresql数据库地址'),password=replace(password,'123456','postgresql数据库密码') where database_type='postgresql';  
```
PS: 执行  umc.sql 发现数据库中的字段值是192.168.7.166，不是127.0.0.1

## 压缩包内，找不到文件
```bash  
cd /app/apache-tomcat-9.0.74/webapps/umc/WEB-INF/classes
  # 进入umc文件夹
  vi application-druid.yml
  # 编辑数据库连接配置文件，并保存退出
```

## 压缩包内，找不到文件
```bash  
  ueh_start.sh .
  ueh_status.sh .
  ueh_stop.sh .
```  
PS: [github  v3.0.0-release](https://github.com/china-alert/ueh/releases/tag/v3.0.0-release) 有上面3个.sh 文件

**Comment by china-alert** [comment]
1. 问题一“mysql postgresql 实际字段参数值错误”，已修复，新介质下载地址http://download.s21i.co99.net/29000100/0/0/ABUIABBPGAAgn9vZugYo4O3H0gE.zip?f=setup-script.zip&v=1733717407
2. 问题二“压缩包内，找不到文件  vi application-druid.yml”，已修复，文档相关章节修改，按照新文档步骤安装即可。
![图片](https://github.com/user-attachments/assets/e10d6a7b-0b8e-482b-89e6-f8eaf264f90a)
3. 问题三“压缩包内，找不到文件  ueh_start.sh .ueh_status.sh .ueh_stop.sh .”，新介质下载地址http://download.s21i.co99.net/29000100/0/0/ABUIABBPGAAg9pPZugYopaLtuwc.zip?f=setup-backend.zip&v=1733708326

**Comment by FeiYuJun** [comment]
服务已启动
```bash
[root@testnode-159 conf]# /app/apache-tomcat-9.0.74/bin/startup.sh
Using CATALINA_BASE:   /app/apache-tomcat-9.0.74
Using CATALINA_HOME:   /app/apache-tomcat-9.0.74
Using CATALINA_TMPDIR: /app/apache-tomcat-9.0.74/temp
Using JRE_HOME:        /usr/local/jdk
Using CLASSPATH:       /app/apache-tomcat-9.0.74/bin/bootstrap.jar:/app/apache-tomcat-9.0.74/bin/tomcat-juli.jar
Using CATALINA_OPTS:
Tomcat started.

[root@testnode-159 apache-tomcat-9.0.74]# ps -ef|grep tomcat
root       730     1 73 17:37 pts/2    00:00:54 /usr/local/jdk/bin/java -Djava.util.logging.config.file=/app/apache-tomcat-9.0.74/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -Dorg.apache.catalina.security.SecurityListener.UMASK=0027 -Dignore.endorsed.dirs= -classpath /app/apache-tomcat-9.0.74/bin/bootstrap.jar:/app/apache-tomcat-9.0.74/bin/tomcat-juli.jar -Dcatalina.base=/app/apache-tomcat-9.0.74 -Dcatalina.home=/app/apache-tomcat-9.0.74 -Djava.io.tmpdir=/app/apache-tomcat-9.0.74/temp org.apache.catalina.startup.Bootstrap start

[root@testnode-159 apache-tomcat-9.0.74]# netstat -lntup|grep 730
tcp6       0      0 :::8080                 :::*                    LISTEN      730/java
tcp6       0      0 127.0.0.1:8005          :::*                    LISTEN      730/java
```
但 控制台 页面无法访问
![image](https://github.com/user-attachments/assets/45315cdc-61d0-49db-b0ce-a2770f32f720)

![image](https://github.com/user-attachments/assets/ca38efe5-a8dc-485c-8566-62040b36f715)

**Comment by china-alert** [comment]
检查域名是否映射到了其它ip，我们的tomcat版本为9.0.74，并非图中显示的8.5.99

**Comment by china-alert** [comment]
![图片](https://github.com/user-attachments/assets/065a80b5-aafb-4f54-92ff-345bf81f7e01)
如图

**Comment by FeiYuJun** [comment]
赞！解析的IP写错了。现在已经能访问了，但提示 账户/密码 问题？
![image](https://github.com/user-attachments/assets/d8c40d75-27c0-4400-b18e-f66feb4aac93)

**Comment by china-alert** [comment]
登录MySQL数据库，执行以下sql修改密码为123456
`UPDATE umc.sys_user t SET t.password = '$2a$10$1bVfC.ghgFfNOhshK77eNeIrniSyIXSlFMoCgoL7MQPstdRmniF/q' WHERE t.user_id = 1`

**Comment by china-alert** [comment]
在消息体中加入如下字段
"ProbeKey": "f006afa0-0b97-11ec-89ad-2753267550e3"

**Comment by FeiYuJun** [comment]
# 调用 api推送告警 成功，但控制台，查不到告警信息
## 调用成功
unixtime(s): 1735540268  --> 北京时间: 2024-12-30 14:41:08
![image](https://github.com/user-attachments/assets/d925f1a6-8bdd-4753-b43e-9a8967d5d495)

## 控制台 没有对应警报信息
![image](https://github.com/user-attachments/assets/1946c3f4-8c43-4e7f-b7b3-4cfb884a5120)

![image](https://github.com/user-attachments/assets/64dae845-4851-4b9d-9077-1def81e9fe73)


> 在消息体中加入如下字段 "ProbeKey": "f006afa0-0b97-11ec-89ad-2753267550e3"

**Comment by china-alert** [comment]
发送的是恢复事件，查询的是告警事件，点一下页面的清空条件
![图片](https://github.com/user-attachments/assets/9ba14651-eae8-4312-ac4d-592d0ebf969d)

**Comment by FeiYuJun** [comment]
也没有，大佬方便加个Q(1105709025)吗
![image](https://github.com/user-attachments/assets/7cdb8c67-45b2-4ee9-b9cd-8e2529af84c1)
